import type { Metadata } from "next";
import Link from "next/link";
import { BlueetherVisual } from "@/components/blueether/BlueetherVisual";
import { ResponsiveImage } from "@/components/media/ResponsiveImage";

export const metadata: Metadata = { title: "Ecosystem", description: "Three ventures across technology, culture and strategic systems. One connected direction.", alternates: { canonical: "/ecosystem" } };

export default function Page() {
  return <main id="main">
    <header className="page-hero container"><span className="kicker">Ecosystem</span><h1>Different layers.<br/><em>One direction.</em></h1><p className="lead">HOMW, LOCK CITY and BLUEETHER operate in distinct spaces. Together they form a connected architecture of technology, culture and strategic intelligence.</p></header>
    <section className="venture-detail light-detail" id="homw"><div className="container detail-layout"><div><span className="tag">01 · Real Estate Technology</span><h2>HOMW</h2><p className="large-copy">Digital sales infrastructure designed to make complex developments clear, immersive and easier to decide.</p><p>HOMW connects spatial storytelling, project intelligence and premium presentation within one interactive environment.</p><div className="actions"><Link className="btn primary" href="/work/homw">View case study ↗</Link><a className="btn" href="https://woehm.com/" target="_blank" rel="noreferrer">Visit HOMW ↗</a></div></div><ResponsiveImage name="homw-hero" alt="HOMW interactive real estate development" width={1935} height={812} treatment="product" fullBleed /></div></section>
    <section className="venture-detail dark-detail" id="lock-city"><div className="container detail-layout reverse"><div><span className="tag">02 · Culture & Fashion</span><h2>LOCK CITY</h2><p className="large-copy">Identity, belonging and symbolism translated into a distinctive cultural fashion project.</p><p>A lock becomes product, protective metaphor and mark of membership—connecting physical objects to a wider cultural language.</p><div className="actions"><Link className="btn light" href="/work/lock-city">View case study ↗</Link><a className="btn dark-outline" href="https://lockcityclothes.com/" target="_blank" rel="noreferrer">Visit Lock City ↗</a></div></div><ResponsiveImage name="lock-main" alt="Lock City campaign" width={1080} height={1920} treatment="cinematic" fullBleed /></div></section>
    <section className="venture-detail blueether-detail" id="blueether"><div className="container detail-layout"><div><span className="tag">03 · Strategic Intelligence & Systems</span><h2>BLUEETHER</h2><p className="large-copy">The connective layer organizing knowledge, ventures and long-term opportunity.</p><p>BLUEETHER is being built as an intelligence and governance system: a way to recognize relationships, protect direction and turn complexity into strategic clarity.</p><Link className="btn light" href="/#opportunity">Discuss a strategic relationship ↗</Link></div><BlueetherVisual /></div></section>
  </main>;
}
